### ISSUE TITLE
Lista pracowników - wyświetlanie

### ISSUE THREAD

**Issue by AlanLes** [mignaszewski/intranet#13]
Od strony usera.
Wyświetlanie listy użytkowników według kategorii, np. tylko pracownicy z Wrocławia, albo tylko pracownicy w projekcie GEA. Oczywiście przy pierwszym wejściu wyświetlanie wszystkich pracowników alfabetycznie, wybór filtru może być po lewej, albo na górze, jak w niektórych sklepach mamy filtrowanie.

**Comment by andziaoo7** [comment]
Wydaje mi się, że można by było po wejściu na kategorię "Pracownicy" pokazać wszystkich pracowników, ale już pogrupowanych, jak to jest tutaj
http://pixers.pl/blog/nasz-zespol (w ogóle świetną mają stronę)
Az boku bądź nad wyświetlonymi pracownikami mogą być zakładki, które grupują i byłyby np. wszyscy | altim | softiti (w zależności czy ich też będziemy uwzględniać) | projekty | zarząd itp itd
Te stronki też są spoko:
https://www.sinch.com/about-us/people/
http://jobs.lifesum.com/people

**Comment by andziaoo7** [comment]
Można też dodać sekcję "Żegnamy się z", "Gratulacje dla", "Witamy w zespole", w której byłoby info o odchodzących pracownikach, tych którzy awansowali lub dopiero co rozpoczęli pracę. Informacje te można dodawać jako aktualności z etykietami o których wspominałam w innym komentarzu. W powyższej formie będzie to jednak pogrupowane i bardziej przejrzyste pod kątem wizualnym. 

Przykład:
http://www.slideshare.net/DigitalWorkplaceGroup/31-intranet-homepage-design-examples-with-screenshots (sajd nr 58)
