### ISSUE TITLE
Szablon strony grafika

### ISSUE THREAD

**Issue by mignaszewski** [mignaszewski/intranet#38]
Zrobienie mockup'u strony wg obecnych trendów.
Grafika w jpg powinna byc zalaczona do zagadnienia.
Ma to byc tylko wyglad strony glownej chodzi o uklad.

**Comment by andziaoo7** [comment]
[Intranet szablon strony głównej 2.pdf](https://github.com/mignaszewski/intranet/files/22324/Intranet.szablon.strony.glownej.2.pdf)
[Intranet szablon strony głównej 3.1.pdf](https://github.com/mignaszewski/intranet/files/22323/Intranet.szablon.strony.glownej.3.1.pdf)
[Intranet szablon strony głównej 3.pdf](https://github.com/mignaszewski/intranet/files/22325/Intranet.szablon.strony.glownej.3.pdf)

[Intranet szablon strony głównej.pdf](https://github.com/mignaszewski/intranet/files/21810/Intranet.szablon.strony.glownej.pdf)

**Comment by andziaoo7** [comment]
[Intranet szablon strony głównej 5.pdf](https://github.com/mignaszewski/intranet/files/22393/Intranet.szablon.strony.glownej.5.pdf)

Dajcie znać czy tak może być, czy coś zmienić :)

**Comment by andziaoo7** [comment]
[Intranet szablon strony głównej 8.pdf](https://github.com/mignaszewski/intranet/files/22528/Intranet.szablon.strony.glownej.8.pdf)

**Comment by andziaoo7** [comment]
[Intranet szablon strony głównej 9.pdf](https://github.com/mignaszewski/intranet/files/23272/Intranet.szablon.strony.glownej.9.pdf)

Wczoraj już poprawiłam ten szablon, ale nie dodałam tutaj.
